# Generated by Django 5.1.6 on 2025-02-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_matric_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('student', 'lecturer')},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assignments', to='api.lecturer'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_round',
        ),
    ]
