# Generated by Django 5.1.6 on 2025-02-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
