# Generated by Django 5.1.6 on 2025-02-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('student', 'Student'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
